## LRE Curves
### Grant B. Morgan
### Baylor University

========================================================

```{r}
lre<-read.csv("C:\\Users\\grant_morgan\\Box Sync\\Research\\Mike Seaman\\minimum_R.csv", header=TRUE)
```

## Normal Distribution
```{r fig.width=7, fig.height=6}
library(ggplot2)

normal<-lre[which(lre$dist=="normal"),]
normal<-normal[which(normal$ID2!=2),]

ggplot(data=normal, aes(x=es, y=LRE, group=test, colour=test, shape=test)) +
    geom_line() +
    geom_point()
```

## Logistic Distribution
```{r fig.width=7, fig.height=6}

logistic<-lre[which(lre$dist=="logistic"),]
logistic<-logistic[which(logistic$ID2!=2),]

ggplot(data=logistic, aes(x=es, y=LRE, group=test, colour=test, shape=test)) +
    geom_line() +
    geom_point()
```

## LaPlace Distribution
```{r fig.width=7, fig.height=6}

dexp<-lre[which(lre$dist=="dexp"),]
dexp<-dexp[which(dexp$ID2!=2),]

ggplot(data=dexp, aes(x=es, y=LRE, group=test, colour=test, shape=test)) +
    geom_line() +
    geom_point()
```

## Uniform Distribution
```{r fig.width=7, fig.height=6}

uniform<-lre[which(lre$dist=="uniform"),]
uniform<-uniform[which(uniform$ID2!=2),]

ggplot(data=uniform, aes(x=es, y=LRE, group=test, colour=test, shape=test)) +
    geom_line() +
    geom_point()
```
